/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdentityProvider } from './identityProvider';


export interface AuthenticationPermit { 
    provider?: IdentityProvider;
    idToken?: string | null;
    deviceId?: string | null;
}

