/**
 * RotmgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateAndTime } from './dateAndTime';


export interface Complaint { 
    id?: string | null;
    fingerprint?: string | null;
    email?: string | null;
    date?: DateAndTime;
    body?: string | null;
}

