/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Item } from './item';
import { Hints } from './hints';
import { Gamemode } from './gamemode';


export interface GameOptions { 
    mode?: Gamemode;
    guesses?: Array<Item> | null;
    allHints?: Array<Hints> | null;
    anagram?: string | null;
    description?: string | null;
    reskinsExcluded?: boolean;
}

