/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Hint } from './hint';


export interface Hints { 
    tier?: Hint;
    type?: Hint;
    numberOfShots?: Hint;
    xpBonus?: Hint;
    feedpower?: Hint;
}

