/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Hint = 'Bigger' | 'Smaller' | 'Correct' | 'Wrong';

export const Hint = {
    Bigger: 'Bigger' as Hint,
    Smaller: 'Smaller' as Hint,
    Correct: 'Correct' as Hint,
    Wrong: 'Wrong' as Hint
};

