/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Item { 
    id?: string | null;
    name?: string | null;
    imageURL?: string | null;
    xmlId?: string | null;
    tier?: string | null;
    description?: string | null;
    reskin?: boolean;
    type?: string | null;
    damageBottom?: number;
    damageTop?: number | null;
    range?: number | null;
    numberOfShots?: number | null;
    xpBonus?: number;
    feedpower?: number;
    tags?: Array<string> | null;
    dominantColor?: string | null;
    colorClass?: string | null;
}

