/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DateAndTime } from './dateAndTime';
import { DetailedGameStatistic } from './detailedGameStatistic';


export interface PlayerProfile { 
    id?: string | null;
    name?: string | null;
    role?: string | null;
    registrationDate?: DateAndTime;
    normalStats?: DetailedGameStatistic;
    dailyStats?: DetailedGameStatistic;
    dailyGuesses?: number;
}

