/**
 * RomgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Game } from './game';
import { GameStatistic } from './gameStatistic';


export interface Player { 
    id?: string | null;
    name?: string | null;
    email?: string | null;
    password?: string | null;
    registrationDate?: string;
    normalStats?: GameStatistic;
    dailyStats?: GameStatistic;
    currentGame?: Game;
    dailyAttempted?: boolean;
}

