/**
 * RotmgleWebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenAuthenticationResultType } from './tokenAuthenticationResultType';


export interface TokenAuthenticationResponse { 
    isAuthenticated?: boolean;
    type?: TokenAuthenticationResultType;
    accessToken?: string | null;
    refreshToken?: string | null;
}

